### ISSUE TITLE
Parse payload error in transaction 0x0b93a8f7ac38c986e9c484fbc2140aeae626a8fa12549591d9c83390d03a5f95

### ISSUE THREAD

**Issue by ValentineReese** [starcoinorg/starcoin-sdk-python#11]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/100587939/157156993-06c50a8e-9e8b-44c2-83ef-edeb98f05a58.png">

`Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/bobong/Codes/block-chain/starcoin/swap/remedy_star_py/main.py", line 109, in <module>
    crawl_all_user_options(begin_block_num=4519144, end_block_num=4520500)
  File "/Users/bobong/Codes/block-chain/starcoin/swap/remedy_star_py/main.py", line 96, in crawl_all_user_options
    users = get_transactions_between(begin_block_num, end_block_num)
  File "/Users/bobong/Codes/block-chain/starcoin/swap/remedy_star_py/main.py", line 68, in get_transactions_between
    users = parse_blocks(start_num, end_num)
  File "/Users/bobong/Codes/block-chain/starcoin/swap/remedy_star_py/main.py", line 57, in parse_blocks
    sender, opt = parser_txn(txn, i)
  File "/Users/bobong/Codes/block-chain/starcoin/swap/remedy_star_py/main.py", line 37, in parser_txn
    payload = starcoin_types.TransactionPayload.bcs_deserialize(payload)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/starcoin_types/__init__.py", line 902, in bcs_deserialize
    v, buffer = bcs.deserialize(input, TransactionPayload)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/bcs/__init__.py", line 117, in deserialize
    value = deserializer.deserialize_any(obj_type)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/serde_binary/__init__.py", line 415, in deserialize_any
    return self.deserialize_any(new_type)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/serde_binary/__init__.py", line 402, in deserialize_any
    field_value = self.deserialize_any(field_type)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/serde_binary/__init__.py", line 402, in deserialize_any
    field_value = self.deserialize_any(field_type)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/serde_binary/__init__.py", line 402, in deserialize_any
    field_value = self.deserialize_any(field_type)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/serde_binary/__init__.py", line 342, in deserialize_any
    length = self.deserialize_len()
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/bcs/__init__.py", line 89, in deserialize_len
    value = self.deserialize_uleb128_as_u32()
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/bcs/__init__.py", line 70, in deserialize_uleb128_as_u32
    byte = int.from_bytes(self.read(1), "little", signed=False)
  File "/Users/bobong/miniforge3/envs/remedy_star/lib/python3.10/site-packages/starcoin/serde_binary/__init__.py", line 235, in read
    raise st.DeserializationError("Input is too short")
starcoin.serde_types.DeserializationError: Input is too short`

**Comment by sanlee42** [comment]
Fixed in https://github.com/starcoinorg/starcoin-sdk-python/commit/0e6d193bd8ef7cdb699cf538f52b1f4d201de0c6
